"""update_SQLAlchemy_unique2

Revision ID: 4dab29ccffb7
Revises: 634f79deab0a
Create Date: 2020-09-19 01:34:56.743867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dab29ccffb7'
down_revision = '634f79deab0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_name', table_name='bhistory')
    op.create_unique_constraint(None, 'bhistory', ['manhua_url'])
    op.alter_column('collection', 'user_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.drop_index('user_name', table_name='collection')
    op.create_unique_constraint(None, 'collection', ['manhua_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection', type_='unique')
    op.create_index('user_name', 'collection', ['user_name'], unique=True)
    op.alter_column('collection', 'user_name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.drop_constraint(None, 'bhistory', type_='unique')
    op.create_index('user_name', 'bhistory', ['user_name'], unique=True)
    # ### end Alembic commands ###
