"""update_SQLAlchemy_unique

Revision ID: b20675fff357
Revises: 9d77c14eac22
Create Date: 2020-09-18 09:27:52.043651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b20675fff357'
down_revision = '9d77c14eac22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bhistory', 'manhua_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('collection', 'manhua_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collection', 'manhua_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('bhistory', 'manhua_url',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
